parameters:
  vmImage: ubuntu-latest
  nodeVersions:
    - 10.0.0
    - 10.x
    - 12.0.0
    - 12.x
  variables: {}
  timeoutMin: 5
  env: {}

jobs:
  - job: ${{ parameters.jobName }}

    pool:
      vmImage: ${{ parameters.vmImage }}

    strategy:
      matrix:
        ${{ each nodeVersion in parameters.nodeVersions }}:
          ${{ format('Node.js {0}', nodeVersion) }}:
            node_version: ${{ nodeVersion }}

    variables: ${{ parameters.variables }}

    steps:
      - template: ../steps/init-node.yml
        parameters:
          nodeVersion: $(node_version)

      - script: ${{ parameters.script }}
        displayName: ${{ parameters.stepLabel }}
        timeoutInMinutes: ${{ parameters.timeoutMin }}
        env: ${{ parameters.env }}

    cancelTimeoutInMinutes: 1
