parameters:
  vmImage: ubuntu-latest
  variables: {}
  timeoutMin: 5
  env: {}

jobs:
  - job: ${{ parameters.jobName }}

    pool:
      vmImage: ${{ parameters.vmImage }}

    variables: ${{ parameters.variables }}

    steps:
      - template: ../steps/init-node.yml

      - script: ${{ parameters.script }}
        displayName: ${{ parameters.stepLabel }}
        timeoutInMinutes: ${{ parameters.timeoutMin }}
        env: ${{ parameters.env }}

    cancelTimeoutInMinutes: 1
